server {
  listen 80;
  location /api/ { proxy_pass http://api:4000/; proxy_set_header Host $host; }
  location /webhooks/ { proxy_pass http://api:4000/webhooks/; proxy_set_header Host $host; }
  location / { proxy_pass http://admin:80/; proxy_set_header Host $host; }
}
